---
- hosts: 172.31.23.195
  become: yes
  tasks:
  - include_tasks: file.yml
  - name: install webserver
    apt:
     name: apache2

  - name: copy index file into node side
    copy:
     src: indexfile
     dest: /var/www/html/index.html  
